services: docker
language: bash
install:
  - env | sort
  - git clone https://github.com/docker-library/official-images.git ~/official-images
  - docker run -it --rm --name nvchecker --mount type=bind,source=${PWD},target=/data/ -w /data -e NVCHECKER_GITHUB_TOKEN=${GH_TOKEN} snw35/nvchecker:latest nvchecker nvchecker.ini
  - docker run -it --rm --name dfupdate --mount type=bind,source=${PWD},target=/data/ -w /data snw35/dfupdate:latest
  - if [[ $(git status --porcelain | wc -l) -eq 0 ]] && [[ -z ${TRAVIS_TAG} ]]; then
      echo "No local changes detected and no tag set, nothing to build, exiting.";
      travis_terminate 0;
    else
      echo "Local changes or tagged commit detected, continuing...";
    fi

before_script:
  - TERRARIA_VERSION=`grep "ENV TERRARIA_VERSION" Dockerfile | cut -d " " -f 3 | head -n 1`
  - CONFD_VERSION=`grep "ENV CONFD_VERSION" Dockerfile | cut -d " " -f 3 | head -n 1`
  - BASE_VERSION=`grep "FROM" Dockerfile | cut -d " " -f 2 | cut -d ":" -f 2`
  - IMAGE="${TRAVIS_REPO_SLUG}:${TERRARIA_VERSION}"
  - PROPOSED_TAG=${TERRARIA_VERSION}-${CONFD_VERSION}-${BASE_VERSION}
  - git config --local user.name "${DOCKER_USERNAME}"
  - git config --local user.email "snw35@use.startmail.com"
  - git remote add upstream https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git > /dev/null 2>&1
  - if [ $(git ls-remote --tags upstream "${PROPOSED_TAG}" | wc -l) -eq 0 ]; then
      echo "Propsoed tag does not exist on remote, continuing.";
    else
      echo "Proposed tag already exists on remote, skipping container build.";
      travis_terminate 0;
    fi

script:
  - env | sort
  - travis_retry docker build -t "$IMAGE" .
  - ~/official-images/test/run.sh "$IMAGE" || travis_terminate 1;
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE"
  - docker tag "$IMAGE" "${TRAVIS_REPO_SLUG}:latest"
  - docker push "${TRAVIS_REPO_SLUG}:latest"

after_script:
  - docker images

before_deploy:
  - cp new_ver.txt old_ver.txt
  - git checkout master
  - git add -A
  - git commit --message "Software Updated"
  - git tag $PROPOSED_TAG
  - git push --quiet --set-upstream upstream
  - git push --tags --quiet --set-upstream upstream

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  skip_cleanup: true
  body: 'base image version: $BASE_VERSION
    travis version: $TERRARIA_VERSION
    image deployed: $IMAGE'

branches:
  except:
  - "/^untagged/"

env:
  global:
  - secure: NXYq3MtCV5IwPbWhH6fpBwTDubQyc0gr6EEM8vxNE5c0bsAL3Io3ncH3p2zEFZh8mByJhj+KPDRdLpCWf84eTSOzV4v09Ntmg9+LbdaI+DeDD34GAmYTKuaABRJubNzrN08PpzTSMOnPHLwVKTyWnYwwdZKo74IRH20TNadOYmHoztS+D1RGc9OAcDm/A9FXkPYRkUKPUNbJU1PrjJAD14C3qw2+YD8At+N8WcciKH/kuwJQ5Js4Oj1QxFXWnIEFtseXqyFbB0Yqj47j61Ssysh2QRs7cFXFjDBmIBaiCF8WNU1knGlEUvnrhaukCMTbqNnGJsGfJYWl7CyK/JXRKIMLp+Hik/LXi1dc+tVbUfs9rHo1S9WIFqTqwZSyTM4nb8D7PyWuxmN6OFAbM+L6nOCyVOPUeI1Ycr+tEgqC/GXHZkzlQYei7pxUxDfOwfmwcwccXw/GbB93MMvp3rNgkcbv5YloBhySMl6QK1xxXdbSZJT43EC4w61TCc+1rTqkXiU/YqK6InVpF0SSBYOwyKCWBZpAbXpZJ/Qt+i7lIOAmgBcWoTWtz6PbaCSQdycORxL8hirOjF2L+MQ8H+1pl4Cx2kPt7L1j4IhqrKvV9q7E6uFAqIsEbD96mDyFl4JFwVznD+POwukjKxzt5x/jfXT+lrKMlB+gn/66nW4XAoU=
  - secure: ka5m+I5wBuIj8pfGI+LMGiW/hHFCWTAHjZ0ucoDdKc4qBAU+36Eb+Yw3zfX0Y16xJBLJbcYUTgx0s6FAeEDpZX00tSZjXVFpuqTBCvFblMpVZxqzGStneK+aqlPZ91zMLteVdQ9+P2TK0aGWRmdKcD53PJ9KS69aGN2esUuEfemXLoyw1ks06F6DZcvhx5mNd3j7X9hS7kkcruKs6cdSf668Ocan0HQEuFzqsixngyq0B5VgGYyNwIA/tVLDLZho1oAC+uXsck8lhwsaIsD3LnBk9+agCvMXXh8aSYUaGnTL22O2Mjx5LVC38oErFoHV350rSQ6Xcbgso6CAZ/TwM2KiR2uJ7E5CZepIDIhL/0BoXFfOztr0K/P9iWhVObBj6wjHXKQcC6nlw/rmV9wLFzM1lN6GF6kRZqM05gMHGrJo1PqH4mOiJoB7nSRz0yvLAmbE9Z3X53DdiZcIw8qVfiuPZPOuop91jbOGJk1v5VkGgsgKAGDsdOWqVd9of5tvQ942vpn9m1i92VkeQA4pRvScByCLMmoeVKGd5SuqUG05Mkg7uFcCF7Sbrap5HacfpLNI8ViHyVQ2cblXYyixcJgATReKVZaKXeulFX0qx1l4KvZ7/dPA6Aas0lxtXbv8bAR8g3ftFQah2oucWguL724YM9XRgaHLn/L2Yrvjr7Q=
  - secure: RyFokx2678chcVL9yQJCFakWAt1qhXy7y624FvdF5ngttVk2d9OEulKDZO8yayvdT5Bpgu/QvIxKWW5GZHObG04ehJ1TXoWB+eA0X4vWS+qXgYeNLcXvqgTn60MUHAi0TrmzVR21ZF6TjahYo1d/Y473iqLyhiZNMSRGqNDMlxRWg8SPjZz7IBTpPzenoLSPoH3eSnPr19IHTQkU6AcpghZP8jGNvIN1Z0jtUnrX8mvGdIyyF+E6tQu+MhWd1lfQHp5u5UEhVej9ved412qQzzeYt2KZGK1GW8Co05Y3wylsoTwufS0T732N/8KRaQ35pOF+U773dNrhZW8a8vP4JlP3tD1C8CBr5BQztqfAWr7D3AIpOZmNAvol4U0O38NkFdv8kehqnHRw1YPav8nezvS3tFAKigSP2+CHbpDGv4tVLGIvgea8G11lO39X5z9/CFZ3y81xR1ai0FDdddrPpiBoraJFSkFwjVbZvYES9RJmnkZUj/6iI2MAJ0zX452t0Wb9qfBw4xA0isl92y9kXJWSNUtVER9txxtMlFhvfi6lEvsHaXEqEFqoU2FjDDog7LIajA8+e15fAEcAvXKZBAOOczOgTuKkn/E1VHffiG9hfeNVhc+enEep2zBrMrgG8rRQNtIYMg5LOYROsYtzTTIfmEdOR6roCx3XUtJhg0Q=
